/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author ESFOT
 */
public class Calcular extends javax.swing.JFrame {

    DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    
         //Figura f2 = new Triangulo(2.4, 1.4);
         //Figura f3 = new Circulo(3.5);
    
    
    
    public Calcular() {
        initComponents();
        
        //lenar combo
        String[] listaFiguras = new String[]{"Cuadrado","Rectangulo","Triangulo","Circulo"};
        for(int i = 0; i < listaFiguras.length; i++){
            
            modeloComboBox.addElement(listaFiguras[i]);
        }
        comboItemsFiguras.setModel(modeloComboBox);
        
        
        
    }
    
    public void panel(boolean bandera){
        panelCuadrado.setEnabled(bandera);
        textLadoARectangulo.setEnabled(bandera);
        textLadoBRectangulo.setEnabled(bandera);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelElijaFigura = new javax.swing.JLabel();
        comboItemsFiguras = new javax.swing.JComboBox<>();
        panelCuadrado = new javax.swing.JPanel();
        labelLado = new javax.swing.JLabel();
        textLadoCuadrado = new javax.swing.JTextField();
        panelRectangulo = new javax.swing.JPanel();
        labelLadoARectangulo = new javax.swing.JLabel();
        labelLadoBRectangulo = new javax.swing.JLabel();
        textLadoARectangulo = new javax.swing.JTextField();
        textLadoBRectangulo = new javax.swing.JTextField();
        panelTriangulo = new javax.swing.JPanel();
        labelLadoATriangulo = new javax.swing.JLabel();
        labelLadoBTriangulo = new javax.swing.JLabel();
        labelLadoCTriangulo = new javax.swing.JLabel();
        textLadoATriangulo = new javax.swing.JTextField();
        textLadoBTriangulo = new javax.swing.JTextField();
        textLadoCTriangulo = new javax.swing.JTextField();
        panelCirculo = new javax.swing.JPanel();
        labelRadioCirculo = new javax.swing.JLabel();
        textRadioCirculo = new javax.swing.JTextField();
        buttonCalcularArea = new javax.swing.JButton();
        labelIngreseDatos = new javax.swing.JLabel();
        labelCuadrado = new javax.swing.JLabel();
        labelRectangulo = new javax.swing.JLabel();
        labelTriangulo = new javax.swing.JLabel();
        labelCirculo = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);

        labelElijaFigura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelElijaFigura.setText("Elija la figura: ");

        comboItemsFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboItemsFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemsFigurasActionPerformed(evt);
            }
        });

        panelCuadrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelLado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLado.setText("Lado:");

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(labelLado))
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(textLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelLado)
                .addGap(18, 18, 18)
                .addComponent(textLadoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRectangulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelLadoARectangulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoARectangulo.setText("Lado A");

        labelLadoBRectangulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoBRectangulo.setText("Lado B");

        javax.swing.GroupLayout panelRectanguloLayout = new javax.swing.GroupLayout(panelRectangulo);
        panelRectangulo.setLayout(panelRectanguloLayout);
        panelRectanguloLayout.setHorizontalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelLadoARectangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectanguloLayout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(textLadoARectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLadoBRectangulo)
                    .addComponent(textLadoBRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        panelRectanguloLayout.setVerticalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLadoARectangulo)
                    .addComponent(labelLadoBRectangulo))
                .addGap(18, 18, 18)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLadoARectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLadoBRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTriangulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelLadoATriangulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoATriangulo.setText("Lado A");

        labelLadoBTriangulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoBTriangulo.setText("Lado B");

        labelLadoCTriangulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLadoCTriangulo.setText("Lado C");

        javax.swing.GroupLayout panelTrianguloLayout = new javax.swing.GroupLayout(panelTriangulo);
        panelTriangulo.setLayout(panelTrianguloLayout);
        panelTrianguloLayout.setHorizontalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrianguloLayout.createSequentialGroup()
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(textLadoATriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textLadoBTriangulo))
                            .addGroup(panelTrianguloLayout.createSequentialGroup()
                                .addComponent(labelLadoATriangulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(labelLadoBTriangulo)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrianguloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textLadoCTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLadoCTriangulo))
                        .addGap(41, 41, 41))))
        );
        panelTrianguloLayout.setVerticalGroup(
            panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrianguloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLadoATriangulo)
                    .addComponent(labelLadoBTriangulo))
                .addGap(16, 16, 16)
                .addGroup(panelTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLadoATriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLadoBTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLadoCTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLadoCTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelCirculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelRadioCirculo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelRadioCirculo.setText("Radio");

        javax.swing.GroupLayout panelCirculoLayout = new javax.swing.GroupLayout(panelCirculo);
        panelCirculo.setLayout(panelCirculoLayout);
        panelCirculoLayout.setHorizontalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRadioCirculo))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelCirculoLayout.setVerticalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelRadioCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonCalcularArea.setText("Calcular Area");
        buttonCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularAreaActionPerformed(evt);
            }
        });

        labelIngreseDatos.setText("Ingrese datos");

        labelCuadrado.setText("Cuadrado");

        labelRectangulo.setText("Rectangulo");

        labelTriangulo.setText("Triangulo");

        labelCirculo.setText("Circulo");

        labelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(labelCuadrado)
                .addGap(92, 92, 92)
                .addComponent(labelRectangulo)
                .addGap(91, 91, 91)
                .addComponent(labelTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCirculo)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelIngreseDatos))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(buttonCalcularArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelElijaFigura)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(panelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(panelRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboItemsFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(panelTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(panelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelElijaFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboItemsFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(labelIngreseDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRectangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuadrado)
                    .addComponent(labelRectangulo)
                    .addComponent(labelTriangulo)
                    .addComponent(labelCirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(buttonCalcularArea)
                .addGap(18, 18, 18)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemsFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemsFigurasActionPerformed
        // TODO add your handling code here:
         
         String figuraFiltrada = (String) comboItemsFiguras.getSelectedItem();
        if( figuraFiltrada.equals("Cuadrado")){
           
            panel(false);
            
            
            //String resu = labelResultado.getName();
            //double res = Double.parseDouble(resu);
            
            
           // String ok = String.valueOf(f1.calcularArea());
            //labelResultado.setName();
            
            
        }
        
          
         
       
            //textLadoARectangulo.setEnabled(false);
               // c.calcularArea();

        
        
        
    }//GEN-LAST:event_comboItemsFigurasActionPerformed

    private void buttonCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularAreaActionPerformed
        // TODO add your handling code here:
        String figuraFiltrada = (String) comboItemsFiguras.getSelectedItem();
        if( figuraFiltrada.equals("Cuadrado")){
           
            
            double ladoC = Double.parseDouble(textLadoCuadrado.getName());
            
            //String resu = labelResultado.getName();
            //double res = Double.parseDouble(resu);
            
            Figura f1 = new Cuadrado(ladoC);
            f1.calcularArea();
           // String ok = String.valueOf(f1.calcularArea());
            //labelResultado.setName();
            
            
        }
            
        
    }//GEN-LAST:event_buttonCalcularAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcularArea;
    private javax.swing.JComboBox<String> comboItemsFiguras;
    private javax.swing.JLabel labelCirculo;
    private javax.swing.JLabel labelCuadrado;
    private javax.swing.JLabel labelElijaFigura;
    private javax.swing.JLabel labelIngreseDatos;
    private javax.swing.JLabel labelLado;
    private javax.swing.JLabel labelLadoARectangulo;
    private javax.swing.JLabel labelLadoATriangulo;
    private javax.swing.JLabel labelLadoBRectangulo;
    private javax.swing.JLabel labelLadoBTriangulo;
    private javax.swing.JLabel labelLadoCTriangulo;
    private javax.swing.JLabel labelRadioCirculo;
    private javax.swing.JLabel labelRectangulo;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTriangulo;
    private javax.swing.JPanel panelCirculo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelRectangulo;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JTextField textLadoARectangulo;
    private javax.swing.JTextField textLadoATriangulo;
    private javax.swing.JTextField textLadoBRectangulo;
    private javax.swing.JTextField textLadoBTriangulo;
    private javax.swing.JTextField textLadoCTriangulo;
    private javax.swing.JTextField textLadoCuadrado;
    private javax.swing.JTextField textRadioCirculo;
    // End of variables declaration//GEN-END:variables
}
